version: '3.9'

services:
  frontend:
    image: ahsandev2019/frontend_custom:1.3
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
    volumes:
      - "../assets:/app/assets"
